save_dir: dataset
allowed_extensions: ["png", "jpg", "jpeg"]

target:
  image_per_collection: 2500

collections_per_category:
  pfp:
    - cryptopunks
    - incognito-nft
    - boredapeyachtclub
    - pudgypenguins
    - clonex
    - doodles-official
    - mutant-ape-yacht-club
    - mypethooligan
    - slotienft
  art:
    - subscapes-by-matt-deslauriers
    - 720-minutes-by-alexis-andre
    - nimbuds-by-bryan-brinkman
    - fidenza-by-tyler-hobbs
    - dreams-by-joshua-bagley
    - algobots-by-stina-jones
    - aerial-view-by-dalenz
    - singularity-by-hideki-tsukamoto
    - fragments-of-an-infinite-field-by-monica-rizzolli
    - geometry-runners-by-rich-lord-1
  collectibles:
    - town-star

negatives:
  pfp: ["art"]
  art: ["pfp"]
