save_dir: dataset
allowed_extensions: ["png", "jpg", "jpeg"]

target:
  image_per_collection: 20

collections_per_category:
  pfp:
    - cryptopunks
    - incognito-nft
    - boredapeyachtclub
    - pudgypenguins
  art:
    - art-blocks-factory

negatives:
  pfp: ["art"]
  art: ["pfp"]
