save_dir: dataset

target:
  image_per_collection: 2500

collections_per_category:
  pfp:
    - cryptopunks
    - incognito-nft
    - boredapeyachtclub
    - pudgypenguins
    - clonex
    - doodles-official
    - mutant-ape-yacht-club
    - mypethooligan
    - slotienft
    - projectnanopass
    - cyberkongz
    - collectvox
    - croakz-v2-1
    - cool-cats-nft
    - cryptoadz-by-gremplin
    - lazy-lions
    - the-doge-pound
    - lostpoets
    - sappy-seals
    - noodlesnft-official

negatives:
  pfp: ["art"]
  art: ["pfp"]
